#!/usr/bin/env python3
"""Scan a software project for software copyright application evidence."""

from __future__ import annotations

import argparse
import json
import os
import re
from collections import Counter
from pathlib import Path
from typing import Any


IGNORE_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "coverage",
    "target",
    "bin",
    "obj",
    "vendor",
}

CODE_EXTS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".vue",
    ".java",
    ".kt",
    ".go",
    ".rs",
    ".cs",
    ".cpp",
    ".c",
    ".h",
    ".hpp",
    ".php",
    ".rb",
    ".swift",
    ".dart",
    ".sql",
    ".html",
    ".css",
    ".scss",
}

DOC_EXTS = {".md", ".txt", ".docx", ".pdf", ".pptx"}
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}

RISK_PATTERNS = [
    ("secret", re.compile(r"(api[_-]?key|secret|password|token)\s*[:=]", re.I)),
    ("placeholder", re.compile(r"(todo|placeholder|lorem ipsum|demo only|待实现|占位)", re.I)),
    ("ai_marker", re.compile(r"(generated by chatgpt|generated by ai|copilot generated|ai generated)", re.I)),
    ("test_account", re.compile(r"(admin123|test123|demo123|root/root)", re.I)),
]

UI_DEP_HINTS = {
    "react": {"react", "react-dom", "next", "vite"},
    "vue": {"vue", "nuxt", "vite"},
    "svelte": {"svelte", "sveltekit"},
    "shadcn": {"shadcn", "class-variance-authority", "radix-ui", "@radix-ui/react-dialog"},
    "material-ui": {"@mui/material", "@material-ui/core"},
    "ant-design": {"antd", "@ant-design/icons"},
    "fluent-ui": {"@fluentui/react", "@fluentui/react-components"},
    "tailwind": {"tailwindcss"},
    "charting": {"echarts", "recharts", "plotly.js", "chart.js"},
    "map-gis": {"leaflet", "openlayers", "mapbox-gl", "cesium"},
    "electron-tauri": {"electron", "@tauri-apps/api"},
}

PY_UI_IMPORTS = {
    "tkinter": re.compile(r"^\s*(import\s+tkinter|from\s+tkinter\s+import)", re.M),
    "customtkinter": re.compile(r"^\s*(import\s+customtkinter|from\s+customtkinter\s+import)", re.M),
    "ttkbootstrap": re.compile(r"^\s*(import\s+ttkbootstrap|from\s+ttkbootstrap\s+import)", re.M),
    "pyside6": re.compile(r"^\s*(import\s+PySide6|from\s+PySide6\s+import)", re.M),
    "pyqt": re.compile(r"^\s*(import\s+PyQt|from\s+PyQt[56]\s+import)", re.M),
    "streamlit": re.compile(r"^\s*import\s+streamlit|^\s*from\s+streamlit\s+import", re.M),
    "gradio": re.compile(r"^\s*import\s+gradio|^\s*from\s+gradio\s+import", re.M),
}


def is_ignored(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def read_text(path: Path, limit: int = 200_000) -> str:
    data = path.read_bytes()[:limit]
    return data.decode("utf-8", errors="replace")


def iter_files(root: Path):
    for path in root.rglob("*"):
        if path.is_dir() or is_ignored(path.relative_to(root)):
            continue
        yield path


def count_lines(path: Path) -> int:
    try:
        return len(read_text(path, limit=2_000_000).splitlines())
    except Exception:
        return 0


def classify(path: Path, root: Path) -> str:
    r = rel(path, root).lower()
    name = path.name.lower()
    if name in {"main.py", "app.py", "index.tsx", "index.jsx", "main.ts", "main.js", "app.vue"}:
        return "entry"
    if any(part in r for part in ("/pages/", "/views/", "/screens/", "/app/")):
        return "page"
    if "/components/" in r:
        return "component"
    if any(part in r for part in ("/api/", "/apis/", "/services/", "/service/")):
        return "service"
    if any(part in r for part in ("/store/", "/stores/", "/model/", "/models/", "/entity/")):
        return "data_model"
    if any(part in r for part in ("/router/", "/routes/", "router.", "routes.")):
        return "route"
    if any(part in r for part in ("/utils/", "/lib/", "/hooks/", "/common/")):
        return "utility"
    if path.suffix.lower() in {".css", ".scss", ".less"}:
        return "style"
    if any(part in r for part in ("/test/", "/tests/", ".spec.", ".test.")):
        return "test"
    return "source"


def category_weight(category: str) -> int:
    return {
        "entry": 0,
        "route": 10,
        "page": 20,
        "service": 30,
        "data_model": 40,
        "component": 50,
        "utility": 60,
        "source": 70,
        "test": 80,
        "style": 90,
    }.get(category, 99)


def load_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return None


def package_facts(root: Path) -> dict[str, Any]:
    for candidate in [root / "package.json", root / "frontend/package.json", root / "client/package.json"]:
        if candidate.exists():
            package = load_json(candidate) or {}
            deps = {}
            for key in ("dependencies", "devDependencies"):
                deps.update(package.get(key) or {})
            return {
                "path": rel(candidate, root),
                "name": package.get("name", ""),
                "version": package.get("version", ""),
                "scripts": package.get("scripts", {}),
                "dependencies": sorted(deps.keys())[:80],
            }
    return {}


def detect_ui_stack(root: Path, code_files: list[Path], package: dict[str, Any]) -> dict[str, Any]:
    deps = set(package.get("dependencies") or [])
    stack: list[str] = []
    evidence: list[str] = []
    for label, hints in UI_DEP_HINTS.items():
        matched = sorted(deps & hints)
        if matched:
            stack.append(label)
            evidence.append(f"{label}: package dependencies {', '.join(matched[:6])}")

    py_hits: dict[str, list[str]] = {}
    for path in code_files[:300]:
        if path.suffix.lower() != ".py":
            continue
        text = read_text(path, limit=160_000)
        for label, pattern in PY_UI_IMPORTS.items():
            if pattern.search(text):
                py_hits.setdefault(label, []).append(rel(path, root))
    for label, paths in py_hits.items():
        stack.append(label)
        evidence.append(f"{label}: {', '.join(paths[:8])}")

    risks: list[str] = []
    if "tkinter" in py_hits and not any(label in py_hits for label in ("customtkinter", "ttkbootstrap")):
        risks.append("检测到原生 Tkinter，但未检测到 CustomTkinter/ttkbootstrap/PySide/PyQt 等视觉增强线索；若为正式 GUI，应补 UI 设计和视觉 QA。")
    if package and not any(label in stack for label in ("shadcn", "material-ui", "ant-design", "fluent-ui", "tailwind")) and any(label in stack for label in ("react", "vue", "svelte")):
        risks.append("检测到 Web 前端框架，但未检测到明确组件库/设计系统依赖；应检查 UI 是否存在自造低质控件。")
    if not stack:
        risks.append("未识别明显 UI 技术栈；如本轮需要截图说明书，应确认是否有可运行界面或可视化入口。")

    return {
        "stack_hints": sorted(set(stack)),
        "evidence": evidence,
        "risks": risks,
    }


def scan_risks(path: Path) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    try:
        text = read_text(path, limit=120_000)
    except Exception:
        return findings
    for label, pattern in RISK_PATTERNS:
        for match in pattern.finditer(text):
            line_no = text[: match.start()].count("\n") + 1
            findings.append({"type": label, "line": str(line_no), "sample": match.group(0)[:80]})
            if len(findings) >= 5:
                return findings
    return findings


def audit(root: Path) -> dict[str, Any]:
    root = root.resolve()
    all_files = list(iter_files(root))
    code_files = [p for p in all_files if p.suffix.lower() in CODE_EXTS]
    doc_files = [p for p in all_files if p.suffix.lower() in DOC_EXTS]
    image_files = [p for p in all_files if p.suffix.lower() in IMAGE_EXTS]

    classes: Counter[str] = Counter()
    extensions: Counter[str] = Counter()
    total_lines = 0
    candidates: list[dict[str, Any]] = []
    risks: list[dict[str, Any]] = []

    for path in code_files:
        line_count = count_lines(path)
        category = classify(path, root)
        classes[category] += 1
        extensions[path.suffix.lower()] += 1
        total_lines += line_count
        candidates.append(
            {
                "path": rel(path, root),
                "category": category,
                "line_count": line_count,
                "priority": category_weight(category),
            }
        )
        file_risks = scan_risks(path)
        if file_risks:
            risks.append({"path": rel(path, root), "findings": file_risks})

    candidates.sort(key=lambda item: (item["priority"], -item["line_count"], item["path"]))

    readmes = [p for p in doc_files if p.name.lower().startswith("readme")]
    package = package_facts(root)
    ui_design = detect_ui_stack(root, code_files, package)

    return {
        "project_root": str(root),
        "package": package,
        "summary": {
            "file_count": len(all_files),
            "code_file_count": len(code_files),
            "source_lines": total_lines,
            "document_count": len(doc_files),
            "image_count": len(image_files),
            "code_extensions": dict(extensions),
            "categories": dict(classes),
        },
        "readme_files": [rel(p, root) for p in readmes[:10]],
        "document_files": [rel(p, root) for p in doc_files[:50]],
        "screenshot_candidates": [rel(p, root) for p in image_files[:50]],
        "ui_design": ui_design,
        "code_candidates": candidates[:200],
        "risk_findings": risks[:80],
    }


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_md(path: Path, data: dict[str, Any]) -> None:
    s = data["summary"]
    lines = [
        "# 项目扫描报告",
        "",
        f"- 项目路径：`{data['project_root']}`",
        f"- 代码文件数：{s['code_file_count']}",
        f"- 源程序行数：{s['source_lines']}",
        f"- 文档文件数：{s['document_count']}",
        f"- 图片/截图候选：{s['image_count']}",
        "",
        "## package 信息",
        "",
    ]
    package = data.get("package") or {}
    if package:
        lines.extend(
            [
                f"- package：`{package.get('path')}`",
                f"- 名称：{package.get('name') or '未识别'}",
                f"- 版本：{package.get('version') or '未识别'}",
                f"- scripts：{', '.join(package.get('scripts', {}).keys()) or '无'}",
            ]
        )
    else:
        lines.append("- 未发现 package.json。")

    lines.extend(["", "## 代码类型分布", ""])
    for key, value in sorted(s["categories"].items()):
        lines.append(f"- {key}: {value}")

    lines.extend(["", "## UI / 产品化线索", ""])
    ui_design = data.get("ui_design") or {}
    stack_hints = ui_design.get("stack_hints") or []
    lines.append(f"- UI 栈线索：{', '.join(stack_hints) if stack_hints else '未识别'}")
    for item in ui_design.get("evidence") or []:
        lines.append(f"- 证据：{item}")
    for item in ui_design.get("risks") or []:
        lines.append(f"- 风险：{item}")

    lines.extend(["", "## 代码抽取候选（前 40）", ""])
    for item in data["code_candidates"][:40]:
        lines.append(f"- `{item['path']}` | {item['category']} | {item['line_count']} 行")

    lines.extend(["", "## 文档证据", ""])
    for item in data["document_files"][:30]:
        lines.append(f"- `{item}`")
    if not data["document_files"]:
        lines.append("- 未发现明显文档。")

    lines.extend(["", "## 截图候选", ""])
    for item in data["screenshot_candidates"][:30]:
        lines.append(f"- `{item}`")
    if not data["screenshot_candidates"]:
        lines.append("- 未发现图片/截图候选。")

    lines.extend(["", "## 风险线索", ""])
    if data["risk_findings"]:
        for risk in data["risk_findings"][:30]:
            samples = "; ".join(f"{f['type']}@{f['line']}" for f in risk["findings"])
            lines.append(f"- `{risk['path']}`: {samples}")
    else:
        lines.append("- 未发现内置规则命中的风险词。")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    parser.add_argument("--out-dir", default="软件著作权申请资料/analysis")
    args = parser.parse_args()

    project = Path(args.project)
    if not project.exists():
        raise SystemExit(f"Project not found: {project}")
    out_dir = Path(args.out_dir)
    data = audit(project)
    write_json(out_dir / "project_audit.json", data)
    write_md(out_dir / "project_audit.md", data)
    print(f"OK project audit: {out_dir}")


if __name__ == "__main__":
    main()
